# Site settings
title: Mario Sobrino Fernandez
twitter_username: ///
name: Mario Sobrino Fernandez

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/SobrinoM
 - title: LinkedIn
   url: www.linkedin.com/in/mariosobrinofernandez
 - title: Thesis
   url: https://www.uantwerpen.be/images/uantwerpen/container2637/files/SobrinoMario-Thesis.pdf
 - title: Kaggle
   url: https://www.kaggle.com/sobrinomario

#Any buzzword skills you want to include
skills:
 - Python
 - R
 - Power BI
 - Matlab
 - C++
 - Feature engineering and predictive modeling 
 - Statsitcs & Mathematics
 - Collibra
 - Data Visualisation

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Data Scientist
   start: 2019
   end: Ongoing
   employer: Axxes
   description: Helping companies to interpret and manage data and to solve complex problems.
 - title: Data Governance Consultant
   start: 2017
   end: 2019
   employer: Inpuls
   description: Inpuls is a consultancy company focusing on all aspects of Information Management & Data Insight.
 - title: PhD Researcher
   start: 2012
   end: 2017
   employer: Condensed Matter Theory group
   description: The CMT research group of Antwerp focuses on nano- and mesoscopic physics, with the goal to characterize materials between the atomic and the macroscopic scale.

#Education is required
education:
 - level: PhD of Science
   date: 2016
   subject: Computational Physics, Confinement induced assembly of anisotropic particles
   school: University of Antwerp

#This section is optional (as is the image link below)
Udemy:
   profileurl: https://www.udemy.com/user/mario-sobrino/
   courses:
    - title: Machine Learning A-Z™ - Hands-On Python & R In Data Science
      link: https://www.udemy.com/machinelearning/
      optionalimage: https://www.udemy.com/machinelearning/
      date: March 2019
Datacamp:
   profileurl: datacamp.com/profile/mariosobrinofernandez
   courses:
    - title: Data Analysis with Python
      link: https://www.datacamp.com/tracks/data-analyst-with-python
      optionalimage: https://assets.datacamp.com/production/tracks/16/badges/original/python-career-track-data-analyst_2x-final.png?1506793799
      date: March 2019
   
#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/sobrinom
   talks:
    - title: Confinement Induced Assembly
      speakerdeckId: 70381f11731c4a569834e7bcdd084644
      conference: Public Defense

#List of interesting Github repo/projects to include - optional
github:
 - robhinds/robhinds.github.io
 - robhinds/ScaLambda
 - robhinds/opinionated-akka-http
 - robhinds/food2vec
 - robhinds/microservices
 - robhinds/spring-social-geeklist
 - robhinds/spring-social-stackoverflow
 - robhinds/genotype
 - robhinds/footweets
 - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  I am a physicist with 6 years experience working in technology. I have primarily worked on data analysis and information management. 
  I have primarily worked with R, but have experience in a broad range of technologies: matlab, python, mathematica, and have done some development in C++. 
  

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: My current role uses Python as the primary language and I have been working with Python for the last five years. I am familiar with a the most common Python libraries for data wrangling and analysis.
   <strong>R & Matlab </strong>: R & Matlab have been the primar languages for solving problems in physics numerically.      
   <strong>PowerBI</strong>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including programming microcontrollers, projects that include the use of public APIs, and cloud platforms such as Azure/AWS. <br/><br/>
   